name: EmeraldStats
main: org.emc.stats.EmeraldStats
version: "1.0.0-SNAPSHOT"
author: WhoIsJeb
description: The statistic-tracking plugin for EmeraldMC.
commands:
  stats:
    description: Test command
    usage: /<command>